# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf25d6c578b07ec88078c1b21eba57bf26f513d74fc0eecd8ceb0afdb55937690c2cb38497f8975778d5d3293c80b9f3d69414ecd448bb6826af36c53bbc61ba

test:
  secret_key_base: 6edc44ad99c53f0db954cd7b8d67e9dcaf64b915b616798ec4d0e027634c6da4421c2ba9b7cf8ed191111be26b614e07403ca39f718aeddbf88271b94bb2c25f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
